role:
  admin: "admin"
  user: "user"
books:
  page: 15
  size: "150x150"
  url: "/assets/anh1.jpg"
  content: 50
  detail_width: "100%"
  avatar_width: "50%"
  marked_book:
    reading: 0
    read: 1
book_form:
  description: 3
avatar: 
  size: 150
  comment_size: 40
rate:
  max_rate: 5
activity:
  trackable:
    request:
      content: "requested a book "
    review:
      content: "reviewed a book "
    comment:
      content: "commented a review "
    userbook:
      content: "marked a book "
    like:
      content: "liked a activity "
    favorite:
      content: "marked favorite a book "
users:
  users_per_page: 15
favorite:
  limit: 24
reviews:
  page: 6
book_link: "http://img4.imagetitan.com/img.php?image=13_216528264f92daa0994e4acc30c594f81e963e4bb2519c74-original.jpeg"
