role:
  admin: "admin"
  user: "user"
books:
  page: 15
  size: "150x150"
  url: "/assets/anh1.jpg"
  content: 50
  detail_width: "100%"
  avatar_width: "50%"
  marked_book:
    reading: 0
    read: 1
book_form:
  description: 3
avatar: 
  size: 150
activity:
  trackable:
    request:
      content: "requested a book "
    review:
      content: "reviewed a book "
    comment:
      content: "commented a review "
    userbook:
      content: "marked a book "
    like:
      content: "liked a activity "
    favorite:
      content: "marked favorite a book "
users:
  users_per_page: 15
